./rtl/Synchronizers/RST_SYNC.v
./rtl/Synchronizers/DATA_SYNC.v
./rtl/CLK_GATE/CLK_GATE.v
./rtl/RegFile/RegFile.v
./rtl/ALU/ALU.v
./rtl/UART/UART_RX/UART_RX_FSM.v
./rtl/UART/UART_RX/UART_RX_data_sampling.v
./rtl/UART/UART_RX/UART_RX_deserializer.v
./rtl/UART/UART_RX/UART_RX_edge_bit_counter.v
./rtl/UART/UART_RX/UART_RX_parity_check.v
./rtl/UART/UART_RX/UART_RX_strt_check.v
./rtl/UART/UART_RX/UART_RX_stop_check.v
./rtl/UART/UART_RX/UART_RX.v
./rtl/SYS_CTRL/SYS_CTRL.v
./rtl/Clock_Divider/clk_div.v
./rtl/ASYNC_FIFO/fifo_mem.v
./rtl/ASYNC_FIFO/rptr_empty.v
./rtl/ASYNC_FIFO/sync_r2w.v
./rtl/ASYNC_FIFO/sync_w2r.v
./rtl/ASYNC_FIFO/wptr_full.v
./rtl/ASYNC_FIFO/ASYNC_FIFO.v
./rtl/PULSE_GEN/PULSE_GEN.v
./rtl/UART/UART_TX/uart_fsm.v
./rtl/UART/UART_TX/uart_mux.v
./rtl/UART/UART_TX/uart_parity_calc.v
./rtl/UART/UART_TX/uart_serializer.v
./rtl/UART/UART_TX/UART_TX.v
./rtl/SYS_TOP/SYS_TOP.v
./tb/SYS_TOP_tb.v
